---
apiVersion: v1
kind: Namespace
metadata:
  name: percona-service-broker
---
apiVersion: v1
kind: Service
metadata:
 name: percona-service-broker
 namespace: percona-service-broker
spec:
 selector:
   app: percona-service-broker
 ports:
 - protocol: TCP
   port: 8081
   targetPort: 8081
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: percona-service-broker
spec:
  url: 'http://percona-service-broker.percona-service-broker.svc.cluster.local:8081'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: percona-service-broker
  namespace: percona-service-broker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: percona-service-broker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: percona-service-broker
subjects:
  - kind: ServiceAccount
    name: percona-service-broker
    namespace: percona-service-broker
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: percona-service-broker
rules:
- apiGroups:
  - pxc.percona.com
  resources:
  - perconaxtradbclusters
  - perconaxtradbclusters/status
  - perconaxtradbclusterbackups
  - perconaxtradbclusterbackups/status
  - perconaxtradbclusterrestores
  - perconaxtradbclusterrestores/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - psmdb.percona.com
  resources:
  - perconaservermongodbs
  - perconaservermongodbs/status
  - perconaservermongodbbackups
  - perconaservermongodbbackups/status
  - perconaservermongodbrestores
  - perconaservermongodbrestores/status
  verbs:
  - get
  - list
  - update
  - watch
  - create
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - get
  - create
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - configmaps
  - services
  - persistentvolumeclaims
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - certmanager.k8s.io
  resources:
  - issuers
  - certificates
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - deletecollection
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: percona-service-broker
  namespace: percona-service-broker
  labels:
    app: percona-service-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: percona-service-broker
  template:
    metadata:
      labels:
        app: percona-service-broker
    spec:
      serviceAccountName: percona-service-broker
      containers:
        - name: percona-service-broker
          image: percona/percona-xtradb-cluster-operator:1.2.0-broker
          ports:
          - containerPort: 8081
          imagePullPolicy: Always
