apiVersion: apps/v1
kind: StatefulSet
metadata:
  generation: 1
  name: test-cluster-rs0
  ownerReferences:
  - apiVersion: psmdb.percona.com/v1
    controller: true
    kind: PerconaServerMongoDB
    name: test-cluster
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: mongod
      app.kubernetes.io/instance: test-cluster
      app.kubernetes.io/managed-by: percona-server-mongodb-operator
      app.kubernetes.io/name: percona-server-mongodb
      app.kubernetes.io/part-of: percona-server-mongodb
      app.kubernetes.io/replset: rs0
  serviceName: test-cluster-rs0
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/component: mongod
        app.kubernetes.io/instance: test-cluster
        app.kubernetes.io/managed-by: percona-server-mongodb-operator
        app.kubernetes.io/name: percona-server-mongodb
        app.kubernetes.io/part-of: percona-server-mongodb
        app.kubernetes.io/replset: rs0
    spec:
      containers:
      - args:
        - --bind_ip_all
        - --auth
        - --dbpath=/data/db
        - --port=27017
        - --replSet=rs0
        - --storageEngine=wiredTiger
        - --relaxPermChecks
        - --sslAllowInvalidCertificates
        - --sslMode=preferSSL
        - --clusterAuthMode=x509
        - --slowms=0
        - --profile=1
        - --wiredTigerIndexPrefixCompression=true
        env:
        - name: SERVICE_NAME
          value: test-cluster
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_REPLSET
          value: rs0
        envFrom:
        - secretRef:
            name: test-cluster-secrets
            optional: false
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - mongodb-healthcheck
            - k8s
            - liveness
          failureThreshold: 12
          initialDelaySeconds: 90
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: mongod
        ports:
        - containerPort: 27017
          name: mongodb
          protocol: TCP
        readinessProbe:
          failureThreshold: 8
          initialDelaySeconds: 10
          periodSeconds: 3
          successThreshold: 1
          tcpSocket:
            port: 27017
          timeoutSeconds: 2
        resources:
          requests:
            cpu: 600m
            memory: 1G
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/db
          name: mongod-data
        - mountPath: /etc/mongodb-secrets
          name: test-cluster-mongodb-keyfile
          readOnly: true
        - mountPath: /etc/mongodb-ssl
          name: ssl
          readOnly: true
        - mountPath: /etc/mongodb-ssl-internal
          name: ssl-internal
          readOnly: true
        workingDir: /data/db
      - command:
        - pbm-agent
        env:
        - name: PBM_AGENT_STORAGES_CONFIG
          value: /etc/percona-backup-mongodb/storages.yml
        - name: PBM_AGENT_STORAGE_CONFIG
          value: /etc/percona-backup-mongodb/storages.yml
        - name: PBM_AGENT_MONGODB_PORT
          value: "27017"
        - name: PBM_AGENT_DEBUG
          value: "true"
        - name: PBM_AGENT_MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              key: MONGODB_BACKUP_USER
              name: test-cluster-secrets
              optional: false
        - name: PBM_AGENT_MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MONGODB_BACKUP_PASSWORD
              name: test-cluster-secrets
              optional: false
        imagePullPolicy: Always
        name: backup-agent
        resources: {}
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/percona-backup-mongodb
          name: test-cluster-backup-agent-config
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
      terminationGracePeriodSeconds: 30
      volumes:
      - name: test-cluster-mongodb-keyfile
        secret:
          defaultMode: 288
          optional: false
          secretName: test-cluster-mongodb-keyfile
      - name: ssl
        secret:
          defaultMode: 288
          optional: false
          secretName: test-cluster-ssl
      - name: ssl-internal
        secret:
          defaultMode: 288
          optional: true
          secretName: test-cluster-ssl-internal
      - name: test-cluster-backup-agent-config
        secret:
          defaultMode: 420
          optional: false
          secretName: test-cluster-backup-agent-config
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: mongod-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 6G
    status:
      phase: Pending
